version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/bfs-web-app"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * fri%2"
      timezone: "Europe/Zurich"
    target-branch: "main"
    commit-message:
      prefix: "[skip cd]"
    labels:
      - "dependencies"
      - "area/web-app"
    groups:
      web-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/bfs-docs"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * fri%2"
      timezone: "Europe/Zurich"
    target-branch: "main"
    commit-message:
      prefix: "[skip cd]"
    labels:
      - "dependencies"
      - "documentation"
    groups:
      web-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gomod"
    directory: "/bfs-backend"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * fri%2"
      timezone: "Europe/Zurich"
    target-branch: "main"
    commit-message:
      prefix: "[skip cd]"
    labels:
      - "dependencies"
      - "area/backend"
    groups:
      go-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "terraform"
    directory: "/bfs-cloud/envs/staging"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * fri%2"
      timezone: "Europe/Zurich"
    target-branch: "main"
    commit-message:
      prefix: "[skip cd]"
    labels:
      - "dependencies"
      - "area/cloud"
    groups:
      terraform-all:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/bfs-cloud/envs/production"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * fri%2"
      timezone: "Europe/Zurich"
    target-branch: "main"
    commit-message:
      prefix: "[skip cd]"
    labels:
      - "dependencies"
      - "area/cloud"
    groups:
      terraform-all:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/bfs-android-app"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * fri%2"
      timezone: "Europe/Zurich"
    target-branch: "main"
    commit-message:
      prefix: "[skip cd]"
    labels:
      - "dependencies"
      - "area/android-app"
    groups:
      android-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
